language: ruby
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: eb6G5rSLaUn1zCIWETG40Wy+LQkh6TbB1fMj/e15z44YpohnThfxZHSip7qinlY770N2K8wtCckvpHXJvUyRNnCvF2GsCYL381eut8YXr68mWSTUjqAECAhAZNJAv1iwle1YpK0VRSsIwkIQKAi4VaKv0DYx3pIFtA02CBzs7Ihgnlc1iIu1Mo92AtjSWw+Y8ksB7klyypiuxZ/Xbtt3+UXqLGM/PT/9VEAwR3JsNUcoeExHhGUiqWnPCTWhMyORuI3RhQAQ/25KPK0zJrG5HylVj1dG8ra9gPFlY1+5ptVZ7204DpPlSN3ijTbAndPhsRJyJEoXOgwoD3Dw5TnrQ8IuxT0LxH0Wq6L9lZ0x1HSkJPxAzedyfXXnhCQnpesKkcVZVTMgIawNiwR6WavUK3+GCK+VOU3k/M5uCG2CWyUTnLhPG7Ea1qx1Ae4ZTwV7kKfbDJ3ndjVsNe6Vf0/tYZdBXHC55F6QhuPlctVp2QtGTaaJyN68TxEaylPPU/zO4gvHwYQCiXYx4/QxW+13ss7t6avbIpmCbpIi1LsDq7XHAlkqvi998BU2JkgdCVbXQRQs9riyeUK101rOTcYoZkk+4GYkj7opcSCzqd1rCzwyCl1gg8i46q5JjrOoxAY5CH4wztoIt5LfCv8ktd3j5K0AZo1RWwu+FetvpmqOW/A=
