### GENERAL SETTINGS ###

# Site settings
title: gvSIG Roads, solución libre para gestión de carreteras
description: "Solución libre e interoperable para la gestión integral de las infraestructuras viarias."
google_analytics: UA-73596417-1 #Google analytics code in the format XX-nnnnnnnn-n
#baseurl: "/roads" #important: start with /
url: "http://www.gvsigroads.com" #pro url
#url: "http://localhost:4000"
ASSET_PATH: /assets

# Build settings
markdown: kramdown
#permalink: /:title/
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is
highlighter: rouge
paginate:    2
paginate_path: "blog/page:num"


colors:  #in hex code if not noted else
  primary: "#3b8bba" #azul claro apagado
  primary_rgb: "59,139,186" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#384452" #azul oscuro
  secondary_rgb: "56,68,82"
  link: "#428bca" #azul claro
  link_hover: "#01b2fe" #azul claro
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3" #gris
  yellow_gvsig: "#E2AD2A"
  title: "#074f66" #azul heading


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  #- title: dribbble
  #  url:
  - title: linkedin
    url: http://www.linkedin.com/grp/home?gid=8478272
  - title: twitter
    url: http://twitter.com/gvsigroads


# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - C/ San Vicente Mártir, 84 - 5A Valencia
    - CP 46002, Spain
    - +34 963 516 309
email: gvsigroads@disid.com
tel: (+34) 963 516 309

# Clients information. Shown on Home and About pages.
clients:
  - name: Asociación gvSIG
    img: asociacion-gvsig.png
    url: http://www.gvsig.com
    title: Asociación gvSIG website
  - name: DISID
    img: disid.png
    url: http://www.disid.com
    title: DISID Corporation website
  - name: Diputación de Valencia
    img: logo-dival.png
    url: http://www.dival.es/
    title: Diputación de Valencia website

# jekyll configuration

gems:
  - jekyll-asciidoc

asciidoc: asciidoctor
asciidoc_ext: asciidoc,adoc,ad

asciidoctor:
  attributes:
    - idseparator=_
    - icons=font-awesome
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style

#
# Multilanguage
#

defaults:
  -
    scope:
      path: ""
    values:
      lang: es
      layout:
  -
    scope:
      path: _posts/en
    values:
      lang: en
      layout:

t:
  en:
    more: "More info"
    # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
    legal-notice: "Legal Notice"
    office: "Our office"
    header:
      title: "gvSIG"
      title-highlight: "Roads"
      description:
      - lines:
        - Open source and interoperable solution
        - for the management of roads
    about:
      title: "What is gvSIG Roads?"
      description:
      - lines:
        - gvSIG Roads ...
        - Implantar gvSIG Roads ...
      # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
      headline: "Comprehensive maintenance management and maintenance of roads using free software with integrated mapping information."
    how:
      title: ""
      description: ""
    features:
      title: ""
      description: ""
    video:
      title:
      - lines:
        -
        -
      headline: ""
    software:
      title: ""
      description:
      - lines:
        - ""
        - ""
      tools:
        - name: gvSIG Desktop
          img: logo_gvsigdesktop.png
          url: http://www.gvsig.com
          description: ""
        - name: gvNIX
          img: logo-gvnix-negativo.png
          url: http://www.gvnix.com
          description: ""
    portfolio:
      title: "REFERENCES"
      description: "Projects and presentations of gvSIG Roads solution"
    clients:
      title: ""
      description: ""

# Cambio idioma

  es:
    more: "Más info"
    legal-notice: Aviso legal
    office: "Nuestras oficinas"
    header:
      title: "gvSIG"
      title-highlight: "Roads"
      description:
      - lines:
        - Solución libre e interoperable
        - para la gestión integral de las infraestructuras viarias
    about:
      title: "¿Qué es gvSIG Roads?"
      description:
      - lines:
        - gvSIG Roads es una solución integral, que permite la gestión de las infraestructuras viarias tanto desde su componente alfanumérica como geográfica, basada en estándares y software libre.
        - Implantar gvSIG Roads permite implantar un completo sistema de gestión para la conservación y el inventario de carreteras integrado con la potencia de las Infraestructuras de Datos Espaciales.
      # Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
      headline: "Gestión integral del mantenimiento y conservación de carreteras utilizando software libre con información cartográfica integrada."
    how:
      title: "Flujo de trabajo con gvSIG Roads"
      description: "Incorpora funcionalidades de carácter gráfico que aportan el concepto GEO así como herramientas de análisis y toma de decisiones."
    features:
      title: "Plataforma tecnológica"
      description: "Se utilizan tecnologías contrastadas, con amplio soporte a nivel internacional, y con una curva evolutiva constante"
    video:
      title:
      - lines:
        - "La mejor solución para la gestión"
        - "de la conservación de carreteras"
      headline: "Gestión de incidencias, inventario y flujo de trabajo con gvSIG Roads"
    software:
      title: "Solución basada en una suite de aplicaciones libres"
      description:
      - lines:
        - "Libre e interoperable."
        - "Dispone de todo el código fuente de las aplicaciones, el acceso a todos los datos que se generen es completo y se basa en el uso de estándares y formatos abiertos, sin coste alguno de licencia."
      tools:
        - name: gvSIG Desktop
          img: logo_gvsigdesktop.png
          url: http://www.gvsig.com
          description: "Software para el manejo de información geográfica con precisión cartográfica"
        - name: gvNIX
          img: logo-gvnix-negativo.png
          url: http://www.gvnix.com
          description: "Herramienta de desarrollo rápido de aplicaciones web Java"
    portfolio:
      title: "REFERENCIAS"
      description: "Proyectos y presentaciones de la solución gvSIG Roads"
    clients:
      title: "DESARROLLADO POR"
      description: "Organizaciones involucradas en el proyecto"

# To include variable in liquid: {{ site.t[page.lang].header.title }}
# You can add translations group

# Links to include in top navigation
# For external links add external: true
links:
  en:
    doc:
#      title: Changelog
#      url: /en/documentation
#      external: false
  es:
    doc:
#      title: Control de cambios
#      url: /es/documentation
#      external: false


include: [".htaccess"]
exclude: ["vendor", "lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]

